name: Build Android AAR

on:
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  pull_request:
    branches:
      - main
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    name: Build AAR
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # 使用 Temurin JDK（原 AdoptOpenJDK）
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build AAR
      run: ./gradlew :sxwebview:assembleRelease  # 确保模块名称和任务名正确

    - name: Upload AAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SxWebView-AAR
        path: sxwebview/sxwebview-release.aar  # 确保路径正确
