name: Build Android AAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    name: Build AAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Clean old build files
      run: rm -rf SxWebView/build/outputs/aar/*

    - name: Build AAR
      run: ./gradlew :sxwebview:assembleRelease

    - name: List build outputs
      run: ls -lR SxWebView/build/outputs/aar/

    - name: Upload AAR as artifact
      uses: actions/upload-artifact@v4
      with:
        name: SxWebView-AAR
        path: SxWebView/build/outputs/aar/*.aar  # 确保上传的是新生成的 AAR
